-- First, clear existing materials to replace with new comprehensive library
DELETE FROM materials_library;

-- Insert Steel materials
INSERT INTO materials_library (material_type, grade, material_number, description) VALUES
('Steel', 'X6Cr13', '1.4000', 'Stainless steel - martensitic'),
('Steel', 'X6CrAl13', '1.4002', 'Stainless steel - martensitic'),
('Steel', 'X2CrNi12', '1.4003', 'Stainless steel - martensitic'),
('Steel', 'X12Cr13', '1.4006', 'Stainless steel - martensitic'),
('Steel', 'X6Cr17', '1.4016', 'Stainless steel - ferritic'),
('Steel', 'X6CrNi17-1', '1.4017', 'Stainless steel - martensitic'),
('Steel', 'X20Cr13', '1.4021', 'Stainless steel - martensitic'),
('Steel', 'X15Cr13', '1.4024', 'Stainless steel - martensitic'),
('Steel', 'X30Cr13', '1.4028', 'Stainless steel - martensitic'),
('Steel', 'X39Cr13', '1.4031', 'Stainless steel - martensitic'),
('Steel', 'X46Cr13', '1.4034', 'Stainless steel - martensitic'),
('Steel', 'X5CrNi18-10', '1.4301', 'Stainless steel - austenitic'),
('Steel', 'X4CrNi18-12', '1.4303', 'Stainless steel - austenitic'),
('Steel', 'X8CrNiS18-9', '1.4305', 'Stainless steel - austenitic'),
('Steel', 'X2CrNi19-11', '1.4306', 'Stainless steel - austenitic'),
('Steel', 'X2CrNi18-9', '1.4307', 'Stainless steel - austenitic'),
('Steel', 'X5CrNiMo17-12-2', '1.4401', 'Stainless steel - austenitic'),
('Steel', 'X2CrNiMo17-12-2', '1.4404', 'Stainless steel - austenitic'),
('Steel', 'C35', '1.0501', 'Carbon steel - unalloyed'),
('Steel', 'C45', '1.0503', 'Carbon steel - unalloyed'),
('Steel', 'C40', '1.0511', 'Carbon steel - unalloyed'),
('Steel', 'C55', '1.0535', 'Carbon steel - unalloyed'),
('Steel', 'C60', '1.0601', 'Carbon steel - unalloyed'),
('Steel', 'S235JR', '1.0038', 'Structural steel - hot rolled'),
('Steel', 'S275JR', '1.0044', 'Structural steel - hot rolled'),
('Steel', 'S355JR', '1.0045', 'Structural steel - hot rolled'),
('Steel', '34CrMo4', '1.7220', 'Alloy steel - chromium molybdenum'),
('Steel', '42CrMo4', '1.7225', 'Alloy steel - chromium molybdenum'),
('Steel', '50CrMo4', '1.7228', 'Alloy steel - chromium molybdenum'),
('Steel', '16MnCr5', '1.7131', 'Case hardening steel'),
('Steel', '20MnCr5', '1.7147', 'Case hardening steel');

-- Insert Aluminum materials  
INSERT INTO materials_library (material_type, grade, description) VALUES
('Aluminum', 'AlCuMg1', 'Aluminum-copper-magnesium alloy'),
('Aluminum', 'AlCuMg2', 'Aluminum-copper-magnesium alloy'),
('Aluminum', 'AlCuMgPb', 'Aluminum-copper-magnesium-lead alloy'),
('Aluminum', 'AlCuSiMg', 'Aluminum-copper-silicon-magnesium alloy'),
('Aluminum', 'AlFeSi', 'Aluminum-iron-silicon alloy'),
('Aluminum', 'AlMg1', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg1.8', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg1SiCu', 'Aluminum-magnesium-silicon-copper alloy'),
('Aluminum', 'AlMg2.5', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg2.7Mn', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMg2Mn0.3', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMg2Mn0.8', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMg3', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg4.5', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg4.5Mn', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMg4Mn', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMg5', 'Aluminum-magnesium alloy'),
('Aluminum', 'AlMg5Mn', 'Aluminum-magnesium-manganese alloy'),
('Aluminum', 'AlMgSi0.5', 'Aluminum-magnesium-silicon alloy'),
('Aluminum', 'AlMgSi0.7', 'Aluminum-magnesium-silicon alloy'),
('Aluminum', 'AlMgSi1', 'Aluminum-magnesium-silicon alloy'),
('Aluminum', 'AlMgSiPb', 'Aluminum-magnesium-silicon-lead alloy'),
('Aluminum', 'AlMn0.5Mg0.5', 'Aluminum-manganese-magnesium alloy'),
('Aluminum', 'AlMn1', 'Aluminum-manganese alloy'),
('Aluminum', 'AlMn1Mg0.5', 'Aluminum-manganese-magnesium alloy'),
('Aluminum', 'AlMn1Mg1', 'Aluminum-manganese-magnesium alloy'),
('Aluminum', 'AlMnCu', 'Aluminum-manganese-copper alloy'),
('Aluminum', 'AlRMg0.5', 'Aluminum-magnesium alloy (refined)'),
('Aluminum', 'AlZn4.5Mg1', 'Aluminum-zinc-magnesium alloy'),
('Aluminum', 'AlZnMg1', 'Aluminum-zinc-magnesium alloy'),
('Aluminum', 'AlZnMgCu0.5', 'Aluminum-zinc-magnesium-copper alloy'),
('Aluminum', 'AlZnMgCu1.5', 'Aluminum-zinc-magnesium-copper alloy'),
('Aluminum', 'G-AlSi10Mg', 'Cast aluminum-silicon-magnesium alloy'),
('Aluminum', 'G-AlSi12', 'Cast aluminum-silicon alloy'),
('Aluminum', 'G-AlSi7Mg', 'Cast aluminum-silicon-magnesium alloy'),
('Aluminum', 'G-AlSi9Cu3', 'Cast aluminum-silicon-copper alloy');

-- Insert Brass/Copper materials
INSERT INTO materials_library (material_type, grade, description) VALUES
('Brass', 'CuAl10Fe2', 'Aluminum brass with iron'),
('Brass', 'CuAl10Fe5Ni5', 'Aluminum brass with iron and nickel'),
('Brass', 'CuAl10Ni3Fe2', 'Aluminum brass with nickel and iron'),
('Brass', 'CuAl11Fe6Ni6', 'Aluminum brass with iron and nickel'),
('Brass', 'CuAl9', 'Aluminum bronze'),
('Bronze', 'CuSn10', 'Tin bronze'),
('Bronze', 'CuSn11P', 'Phosphor tin bronze'),
('Bronze', 'CuSn12', 'Tin bronze'),
('Bronze', 'CuSn12Ni2', 'Tin bronze with nickel'),
('Bronze', 'CuSn5Zn5Pb5', 'Tin-zinc-lead bronze'),
('Bronze', 'CuSn6Zn4Pb2', 'Tin-zinc-lead bronze'),
('Bronze', 'CuSn7Zn2Pb3', 'Tin-zinc-lead bronze'),
('Bronze', 'CuSn7Zn4Pb7', 'Tin-zinc-lead bronze'),
('Bronze', 'CuSn10Pb10', 'Leaded tin bronze'),
('Bronze', 'CuSn11Pb2', 'Leaded tin bronze'),
('Bronze', 'CuSn3Zn8Pb5', 'Tin-zinc-lead bronze'),
('Bronze', 'CuSn5Pb20', 'High-lead tin bronze'),
('Bronze', 'CuSn5Pb9', 'Leaded tin bronze'),
('Bronze', 'CuSn7Pb15', 'High-lead tin bronze'),
('Brass', 'CuZn16Si4', 'Silicon brass'),
('Brass', 'CuZn33Pb2', 'Leaded brass'),
('Brass', 'CuZn33Pb2Si', 'Leaded silicon brass'),
('Brass', 'CuZn35Pb2Al', 'Leaded aluminum brass'),
('Brass', 'CuZn37Al1', 'Aluminum brass'),
('Brass', 'CuZn37Pb2Ni1AlFe', 'Complex leaded brass'),
('Brass', 'CuZn38Al', 'Aluminum brass'),
('Brass', 'CuZn39Pb1Al', 'Leaded aluminum brass'),
('Brass', 'CuZn39Pb1AlB', 'Leaded aluminum brass with boron'),
('Brass', 'CuZn25Al5Mn4Fe3', 'High-strength aluminum brass'),
('Brass', 'CuZn32Al2Mn2Fe1', 'Manganese aluminum brass'),
('Brass', 'CuZn34Mn3Al2Fe1', 'Manganese aluminum brass'),
('Brass', 'CUZn35Mn2Al1Fe1', 'Manganese aluminum brass');