// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nebgrdwjheeuactkcebw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYmdyZHdqaGVldWFjdGtjZWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjk4MzIsImV4cCI6MjA3MDg0NTgzMn0.qiwQR6T0IgFge1L4-MQ2FEeMe0kdQ7ni14WnGQXz2Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});